<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2012 NVIDIA Corporation.  All Rights Reserved.

     NVIDIA Corporation and its licensors retain all intellectual property and
     proprietary rights in and to this software and related documentation.  Any
     use, reproduction, disclosure or distribution of this software and related
     documentation without an express license agreement from NVIDIA Corporation
     is strictly prohibited.
 */
-->
<!DOCTYPE AudioConfigs [
  <!ELEMENT AudioConfigs (alsa_device)>
  <!ELEMENT alsa_device (pcm_config, playback, capture, voice-call, fm)>
  <!ELEMENT playback (pcm_config, device, path)>
  <!ELEMENT capture (pcm_config, device, path)>
  <!ELEMENT voice-call (pcm_config, device, path)>
  <!ELEMENT fm (pcm_config, device, path)>
  <!ELEMENT device (path)>
  <!ELEMENT path (ctl)>
  <!ELEMENT alsa_device EMPTY>
  <!ATTLIST alsa_device name (music|voice|aux|voice-call|bt-voice-call|fm-voice) #REQUIRED>
  <!ATTLIST alsa_device card_id CDATA #REQUIRED>
  <!ATTLIST alsa_device card_name CDATA #REQUIRED>
  <!ATTLIST alsa_device device_id CDATA #REQUIRED>
  <!ELEMENT alsa_device EMPTY>
  <!ELEMENT pcm_config EMPTY>
  <!ATTLIST pcm_config rate (8000|11025|16000|22050|32000|44100|48000|64000|88200|96000|176400|192000) #IMPLIED>
  <!ATTLIST pcm_config channels (1|2|3|4|5|6|7|8) #IMPLIED>
  <!ATTLIST pcm_config bps (16|32) #IMPLIED>
  <!ATTLIST pcm_config period_size CDATA #IMPLIED>
  <!ATTLIST pcm_config period_count CDATA #IMPLIED>
  <!ATTLIST pcm_config start_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config stop_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config silence_threshold CDATA #IMPLIED>
  <!ATTLIST pcm_config avail_min CDATA #IMPLIED>
  <!ELEMENT pcm_config EMPTY>
  <!ELEMENT device EMPTY>
  <!ATTLIST device name (speaker|headphone|earpiece|bt-sco|aux|builtin-mic|headset-mic|bt-sco-mic|voice-call|bt-voice-call|fm-out) #REQUIRED>
  <!ELEMENT device EMPTY>
  <!ELEMENT path EMPTY>
  <!ATTLIST path name CDATA #IMPLIED>
  <!ELEMENT path EMPTY>
  <!ELEMENT param EMPTY>
  <!ATTLIST param name CDATA #REQUIRED>
  <!ATTLIST param val CDATA #REQUIRED>
  <!ELEMENT param EMPTY>
  <!ELEMENT ctl EMPTY>
  <!ATTLIST ctl name CDATA #REQUIRED>
  <!ATTLIST ctl val CDATA #REQUIRED>
  <!ELEMENT ctl EMPTY>
  <!ELEMENT at EMPTY>
  <!ATTLIST at node CDATA #REQUIRED>
  <!ATTLIST at cmd CDATA #REQUIRED>
  <!ELEMENT at EMPTY>
]>
<!--
     This file is used to declare various board specific audio configs
-->

<AudioConfigs>
  <alsa_device name="music"
               card_id="-1"
               card_name="tegramax98090"
               device_id="0">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>


    <param name="ulp" val="1"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="nvoice" val="0"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="I2S Master" val="1"/>

    <path>
      <ctl name="Enhanced Volume Smoothing" val="Disabled"/>
      <ctl name="Digital EQ Clipping Detection" val="Disabled"/>
    </path>

    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>
          <ctl name="Headphone Left Volume" val="10"/>
          <ctl name="Headphone Right Volume" val="10"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Left Speaker Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Left Switch" val="1"/>
          <ctl name="Speaker Right Switch" val="1"/>
	  <ctl name="ALC Compression Ratio" val="1"/>
          <ctl name="ALC Compression Threshold Volume" val="2"/>
          <ctl name="ALC Enable" val="1"/>
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Speaker Left Volume" val="20"/>
          <ctl name="Speaker Right Volume" val="20"/>
        </path>
        <path name="off">
          <ctl name="Left Speaker Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="0"/>
          <ctl name="Speaker Left Switch" val="0"/>
          <ctl name="Speaker Right Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
	  <ctl name="ALC Enable" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Left Receiver Mixer Left DAC Switch" val="1"/>
          <ctl name="Left Receiver Mixer Right DAC Switch" val="1"/>
          <ctl name="Receiver Left Switch" val="1"/>
          <ctl name="Receiver Left Volume" val="25"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="Receiver Left Switch" val="0"/>
        </path>
      </device>
    </playback>

    <param name="call capture rate" val="16000"/>

    <capture>
      <pcm_config start_threshold="1"/>

      <device name="builtin-mic">
        <path name="on">
          <ctl name="External MIC Mux" val="MIC2"/>
          <ctl name="LINEB Mixer IN2 Switch" val="0"/>
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="DMic Sec Switch" val="0"/>
	  <ctl name="MIC1 Boost Volume" val="2"/>
          <ctl name="MIC1 Volume" val="2"/>
	  <ctl name="ADCL Boost Volume" val="1"/>
          <ctl name="ADCR Boost Volume" val="1"/>
          <ctl name="ADCL Volume" val="2"/>
          <ctl name="ADCR Volume" val="2"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <ctl name="Right ADC Mixer MIC1 Switch" val="1"/>
          <ctl name="Left Speaker Mixer MIC1 Switch" val="1"/>                                      
          <ctl name="Right Speaker Mixer MIC1 Switch" val="1"/>
          <ctl name="Left Speaker Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Left Switch" val="1"/>
          <ctl name="Speaker Right Switch" val="1"/>                                  
	  <ctl name="ALC Compression Ratio" val="1"/>
          <ctl name="ALC Compression Threshold Volume" val="5"/>
          <ctl name="ALC Enable" val="1"/>
          <ctl name="Int Spk Switch" val="1"/> 
          <ctl name="Speaker Left Volume" val="9"/>                                                
         <ctl name="Speaker Right Volume" val="9"/>                                        
        </path>
        <path name="off">
	  <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC1 Volume" val="0"/>
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Right ADC Mixer MIC1 Switch" val="0"/>
          <ctl name="Left Speaker Mixer MIC1 Switch" val="0"/>                                      
          <ctl name="Right Speaker Mixer MIC1 Switch" val="0"/> 
          <ctl name="Left Speaker Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="0"/>
          <ctl name="Speaker Left Switch" val="0"/>
          <ctl name="Speaker Right Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
          <ctl name="ALC Enable" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
	   <ctl name="MIC Bias VCM Bandgap" val="1"/>                                                  
          <ctl name="External MIC Mux" val="2"/>
          <ctl name="MIC2 Boost Volume" val="2"/>                                                     
          <ctl name="MIC2 Volume" val="12"/>                                                           
          <ctl name="MIC2 Mux" val="IN34"/>                                                           
	   <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>                                            
          <ctl name="Right ADC Mixer MIC2 Switch" val="1"/>                                           
          <ctl name="Mic Jack Switch" val="1"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>                                                 
          <ctl name="Left Headphone Mixer MIC2 Switch" val="1"/>                                      
          <ctl name="Right Headphone Mixer MIC2 Switch" val="1"/>
          <ctl name="MIXHPRSEL Mux" val="HP Mixer"/>                                      
          <ctl name="MIXHPLSEL Mux" val="HP Mixer"/>                                    
          <ctl name="Headphone Left Volume" val="8"/>                                                
         <ctl name="Headphone Right Volume" val="8"/>                                               
         <ctl name="Headphone Jack Switch" val="1"/>                                                 
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="MIXHPRSEL Mux" val="DAC Only"/>                                      
          <ctl name="MIXHPLSEL Mux" val="DAC Only"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="Right ADC Mixer MIC2 Switch" val="0"/>
          <ctl name="Right Headphone Mixer MIC2 Switch" val="0"/>
          <ctl name="Left Headphone Mixer MIC2 Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
          <ctl name="Headphone Jack Switch" val="0"/>

        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegramax98090"
               device_id="1">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>

  <alsa_device name ="aux"
             card_id="-1"
             card_name="Tegra"
             device_id="3">
    <pcm_config rate="48000"
            channels="2"
            bps="16"
            period_size="1024"
            period_count="4"
            start_threshold="4095"
            stop_threshold="4096"
            silence_threshold="0"
            avail_min="1"/>
    <param name="HW Rates" val="48000 44100"/>
    <playback>
      <device name="aux"/>
    </playback>
  </alsa_device>

<alsa_device name="wfd">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"/>
    <playback>
      <device name="wfd"/>
    </playback>
</alsa_device>

  <alsa_device name="voice-call"
               card_id="-1"
               card_name="tegramax98090"
               device_id="2">
    <pcm_config rate="16000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <at node="/dev/ttySHM2" type="VOLUME" cmd="at+clvl="/>
      <at node="/dev/ttySHM2" type="IN_CALL" cmd="at%iapvc="/>

      <device name="headphone">
        <path name="on">
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>
          <ctl name="Headphone Left Volume" val="15"/>
          <ctl name="Headphone Right Volume" val="15"/>
          <ctl name="Headphone Jack Switch" val="1"/>
          <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=1\r\n"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Left Speaker Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Left Switch" val="1"/>
          <ctl name="Speaker Right Switch" val="1"/>
          <ctl name="Speaker Left Volume" val="39"/>
          <ctl name="Speaker Right Volume" val="39"/>
	  <ctl name="ALC Compression Ratio" val="3"/>
          <ctl name="ALC Compression Threshold Volume" val="20"/>
          <ctl name="ALC Enable" val="1"/>
          <ctl name="Int Spk Switch" val="1"/>
          <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=2\r\n"/>
        </path>
        <path name="off">
          <ctl name="Speaker Left Switch" val="0"/>
          <ctl name="Speaker Right Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
	  <ctl name="ALC Enable" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
	  <ctl name="LINMOD Mux" val="Left Only"/>
          <ctl name="Left Receiver Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="1"/>
          <ctl name="Receiver Left Switch" val="1"/>
          <ctl name="Receiver Right Switch" val="1"/>
          <ctl name="Receiver Left Volume" val="22"/>
          <ctl name="Receiver Right Volume" val="22"/>
          <ctl name="Earpiece Switch" val="1"/>
          <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=0\r\n"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="Receiver Left Switch" val="0"/>
          <ctl name="Receiver Right Switch" val="0"/>
        </path>
      </device>
    </call>

    <call>
      <pcm_config start_threshold="1"/>
      <at node="/dev/ttySHM2" type="MUTE" cmd="at+cmut="/>
      <at node="/dev/ttySHM2" type="CALL_RECORD" cmd="at%ia2prt="/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Int Mic Switch" val="1"/>
          <ctl name="Ext Mic Switch" val="1"/>
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="DMic Sec Switch" val="0"/>
          <ctl name="LINEB Mixer IN2 Switch" val="0"/>
          <ctl name="MIC2 Mux" val="IN56"/>
          <ctl name="MIC1 Mux" val="IN12"/>
          <ctl name="External MIC Mux" val="MIC2"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC2 Volume" val="16"/>
          <ctl name="MIC1 Volume" val="16"/>
	  <ctl name="ADCL Boost Volume" val="0"/>
          <ctl name="ADCR Boost Volume" val="0"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="1"/>
          <ctl name="Right ADC Mixer MIC2 Switch" val="1"/>

        </path>
        <path name="off">
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="DMic Sec Switch" val="0"/>
          <ctl name="Left ADC Mixer MIC1 Switch" val="0"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Int Mic Switch" val="0"/>
          <ctl name="Ext Mic Switch" val="0"/>
          <ctl name="External MIC Mux" val="0"/>
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="DMic Sec Switch" val="0"/>
          <ctl name="LINEB Mixer IN2 Switch" val="0"/>
          <ctl name="MIC2 Mux" val="IN34"/>
          <ctl name="MIC1 Mux" val="IN12"/>
          <ctl name="MIC2 Boost Volume" val="0"/>
          <ctl name="MIC1 Boost Volume" val="0"/>
          <ctl name="MIC2 Volume" val="4"/>
          <ctl name="MIC1 Volume" val="4"/>
	  <ctl name="ADCL Boost Volume" val="2"/>
          <ctl name="ADCR Boost Volume" val="2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="1"/>
          <ctl name="Right ADC Mixer MIC2 Switch" val="1"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="Left ADC Mixer MIC2 Switch" val="0"/>
        </path>
      </device>
    </call>
  </alsa_device>

  <alsa_device name ="bt-voice-call"
           card_id="-1"
           card_name="tegramax98090"
           device_id="3">
    <pcm_config rate="8000"
            channels="1"
            bps="16"
            period_size="256"
            period_count="4"
            start_threshold="1023"
            stop_threshold="1024"
            silence_threshold="0"
            avail_min="1"/>

    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
      </path>

      <at node="/dev/ttySHM2" type="VOLUME" cmd="at+clvl="/>
      <at node="/dev/ttySHM2" type="IN_CALL" cmd="at%iapvc="/>

      <device name="bt-sco">
        <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=4\r\n"/>
      </device>
   </call>
    <call>
      <at node="/dev/ttySHM2" type="MUTE" cmd="at+cmut="/>
      <at node="/dev/ttySHM2" type="CALL_RECORD" cmd="at%ia2prt="/>
      <device name="bt-sco-mic"/>
    </call>
  </alsa_device>

<alsa_device name="fm-voice"
               card_id="-1"
               card_name="tegramax98090"
               device_id="4">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>
    <fm>
      <path name="on">
        <ctl name="FM Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="FM Mode Switch" val="0"/>
      </path>
      <device name="headphone">
        <path name="on">
          <ctl name="Left Headphone Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="1"/>
          <ctl name="Headphone Left Volume" val="26"/>
          <ctl name="Headphone Right Volume" val="26"/>
          <ctl name="Headphone Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
          <ctl name="Left Headphone Mixer Left DAC Switch" val="0"/>
          <ctl name="Right Headphone Mixer Right DAC Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Left Speaker Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Speaker Mixer Right DAC Switch" val="1"/>
          <ctl name="Speaker Left Switch" val="1"/>
          <ctl name="Speaker Right Switch" val="1"/>
          <ctl name="Speaker Left Volume" val="36"/>
          <ctl name="Speaker Right Volume" val="36"/>
	  <ctl name="ALC Compression Ratio" val="3"/>
          <ctl name="ALC Compression Threshold Volume" val="20"/>
          <ctl name="ALC Enable" val="1"/>
          <ctl name="Int Spk Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Speaker Left Switch" val="0"/>
          <ctl name="Speaker Right Switch" val="0"/>
          <ctl name="Int Spk Switch" val="0"/>
	  <ctl name="ALC Enable" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="Left Receiver Mixer Left DAC Switch" val="1"/>
          <ctl name="Right Receiver Mixer Right DAC Switch" val="1"/>
          <ctl name="Receiver Left Switch" val="1"/>
          <ctl name="Receiver Right Switch" val="1"/>
          <ctl name="Receiver Left Volume" val="20"/>
          <ctl name="Receiver Right Volume" val="20"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="Receiver Left Switch" val="0"/>
          <ctl name="Receiver Right Switch" val="0"/>
        </path>
      </device>
    </fm>

    <fm>
      <pcm_config start_threshold="1"/>
      <at node="/dev/ttySHM2" type="MUTE" cmd="at+cmut="/>
      <at node="/dev/ttySHM2" type="CALL_RECORD" cmd="at%ia2prt="/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="ADCL Boost Volume" val="3"/>
          <ctl name="ADCR Boost Volume" val="3"/>
          <ctl name="ADCL Volume" val="3"/>
          <ctl name="ADCR Volume" val="3"/>
          <ctl name="DMIC3 Boost Volume" val="3"/>
          <ctl name="DMIC4 Boost Volume" val="3"/>
          <ctl name="DMIC3 Volume" val="3"/>
          <ctl name="DMIC4 Volume" val="3"/>
          <ctl name="DAI TDM ADCL Slot" val="0"/>
          <ctl name="DAI TDM MIC3 Slot" val="1"/>
          <ctl name="DAI TDM ADCR Slot" val="2"/>
          <ctl name="DAI TDM MIC4 Slot" val="3"/>
          <ctl name="DMic Pri Switch" val="1"/>
          <ctl name="DMic Sec Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="DMic Sec Switch" val="0"/>
          <ctl name="DAI TDM ADCL Slot" val="0"/>
          <ctl name="DAI TDM ADCR Slot" val="1"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="DMic Pri Switch" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="1"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="1"/>
          <ctl name="ADCL Boost Volume" val="2"/>
          <ctl name="ADCR Boost Volume" val="2"/>
          <ctl name="ADCL Volume" val="12"/>
          <ctl name="ADCR Volume" val="12"/>
          <ctl name="Mic Jack Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="Left ADC Mixer IN34 Switch" val="0"/>
          <ctl name="Right ADC Mixer IN34 Switch" val="0"/>
        </path>
      </device>
    </fm>
  </alsa_device>

  <alsa_device name="music"
               card_id="-1"
               card_name="tegraaic325x"
               device_id="0">
    <pcm_config rate="48000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>

    <param name="ulp" val="1"/>
    <param name="ulp formats" val="mp3 aac"/>
    <param name="ulp rates" val="48000 44100"/>
    <param name="HW Rates" val="48000 44100"/>
    <param name="I2S Master" val="1"/>

    <path>
      <!-- playback paths-->
      <ctl name="Line Driver Gain" val="12"/>
      <ctl name="HP Driver Gain" val="7"/>
      <ctl name="DAC Digital Volume Control" val="120"/>
      <ctl name="LOR Output Mixer R_DAC switch" val="1"/>
      <ctl name="LOL Output Mixer L_DAC switch" val="1"/>
      <!-- capture paths-->
      <ctl name="Right ADC Route" val="Digital"/>
      <ctl name="Left ADC Route" val="Digital"/>
      <ctl name="ADC Digital Volume Control" val="44"/>
    </path>
    <playback>
      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
         <ctl name="Codec Firmware Setmode" val="Music Playback Headphones"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Int Spk Switch" val="1"/>
          <ctl name="Codec Firmware Setmode" val="Music Playback Speaker"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="HP Driver Gain" val="7"/>
          <ctl name="HPL Output Mixer L_DAC switch" val="1"/>
          <ctl name="HPR Output Mixer R_DAC switch" val="1"/>
          <ctl name="DAC Digital Volume Control" val="170"/>
          <ctl name="Codec Firmware Setmode" val="Modem Call Receiver"/>
          <ctl name="Earpiece Switch" val="1"/>
        </path>
        <path name="off">
          <ctl name="Earpiece Switch" val="0"/>
          <ctl name="HPL Output Mixer L_DAC switch" val="0"/>
          <ctl name="HPR Output Mixer R_DAC switch" val="0"/>
          <ctl name="DAC Digital Volume Control" val="120"/>
        </path>
      </device>
    </playback>

    <param name="call capture rate" val="16000"/>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="builtin-mic">
        <path name="on">
          <ctl name="Right ADC Route" val="Digital"/>
          <ctl name="Left ADC Route" val="Digital"/>
          <ctl name="Codec Firmware Setmode" val="Voice Record On Board Mic"/>
        </path>
        <path name="off">
         <ctl name="Right ADC Route" val="Analog"/>
         <ctl name="Left ADC Route" val="Analog"/>
        </path>
      </device>
      <device name="headset-mic">
        <path name="on">
          <ctl name="Right Input Mixer IN3_L switch" val="1"/>
          <ctl name="Right Input Mixer IN3_R switch" val="1"/>
          <ctl name="Left Input Mixer CM1L switch" val="1"/>
          <ctl name="Mic_Bias_Power_ctrl" val="1"/>
          <ctl name="Right ADC Route" val="Analog"/>
          <ctl name="Left ADC Route" val="Analog"/>
          <ctl name="MicPGA Volume Control" val="75"/>
          <ctl name="Mic Jack Switch" val="1"/>
          <ctl name="Codec Firmware Setmode" val="Voice Record Headset Mic"/>
        </path>
        <path name="off">
          <ctl name="Mic Jack Switch" val="0"/>
          <ctl name="Mic_Bias_Power_ctrl" val="0"/>
          <ctl name="Right Input Mixer IN3_L switch" val="0"/>
          <ctl name="Right Input Mixer IN3_R switch" val="0"/>
          <ctl name="Left Input Mixer CM1L switch" val="0"/>
          <ctl name="Right Input Mixer CM1R switch" val="0"/>
        </path>
      </device>
    </capture>
  </alsa_device>

  <alsa_device name="voice"
               card_id="-1"
               card_name="tegraaic325x"
               device_id="1">
    <pcm_config rate="8000"
                channels="1"
                bps="16"
                period_size="256"
                period_count="4"
                start_threshold="1023"
                stop_threshold="1024"
                silence_threshold="0"
                avail_min="1"/>
    <playback>
      <device name="bt-sco"/>
    </playback>

    <capture>
      <pcm_config start_threshold="1"/>
      <device name="bt-sco-mic"/>
    </capture>
  </alsa_device>


  <alsa_device name="voice-call"
               card_id="-1"
               card_name="tegraaic325x"
               device_id="2">
    <pcm_config rate="16000"
                channels="2"
                bps="16"
                period_size="1024"
                period_count="4"
                start_threshold="4095"
                stop_threshold="4096"
                silence_threshold="0"
                avail_min="1"/>
    <path>
      <!-- playback paths-->
      <ctl name="Line Driver Gain" val="12"/>
      <ctl name="HP Driver Gain" val="7"/>
      <ctl name="DAC Digital Volume Control" val="120"/>
      <ctl name="LOR Output Mixer R_DAC switch" val="1"/>
      <ctl name="LOL Output Mixer L_DAC switch" val="1"/>
      <!-- capture paths-->
      <ctl name="Right ADC Route" val="Digital"/>
      <ctl name="Left ADC Route" val="Digital"/>
      <ctl name="ADC Digital Volume Control" val="44"/>
    </path>
    <call>
      <path name="on">
        <ctl name="Call Mode Switch" val="1"/>
      </path>
      <path name="off">
        <ctl name="Call Mode Switch" val="0"/>
        <ctl name="Codec Firmware Setmode" val="Music Playback Speaker"/>
      </path>

      <at node="/dev/ttySHM2" type="VOLUME" cmd="at+clvl="/>
      <at node="/dev/ttySHM2" type="IN_CALL" cmd="at%iapvc="/>

      <device name="headphone">
        <path name="on">
          <ctl name="Headphone Jack Switch" val="1"/>
          <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=1\r\n"/>
          <ctl name="Codec Firmware Setmode" val="Modem Call Headset"/>
        </path>
        <path name="off">
          <ctl name="Headphone Jack Switch" val="0"/>
        </path>
      </device>
      <device name="speaker">
        <path name="on">
          <ctl name="Codec Firmware Setmode" val="Modem Call Speaker"/>
          <ctl name="Int Spk Switch" val="1"/>
          <at  node="/dev/ttySHM2" type="PROFILE" cmd="at%iaudcnf=2\r\n"/>
        </path>
        <path name="off">
          <ctl name="Int Spk Switch" val="0"/>
        </path>
      </device>
      <device name="earpiece">
        <path name="on">
          <ctl name="DAC Digital Volume Control" val="170"/>